// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: InternalSerialization.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace serialize.protos {

  /// <summary>Holder for reflection information generated from InternalSerialization.proto</summary>
  public static partial class InternalSerializationReflection {

    #region Descriptor
    /// <summary>File descriptor for InternalSerialization.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static InternalSerializationReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChtJbnRlcm5hbFNlcmlhbGl6YXRpb24ucHJvdG8SCnRleHRzZWN1cmUaE1Np",
            "Z25hbFNlcnZpY2UucHJvdG8i5AEKGVNpZ25hbFNlcnZpY2VDb250ZW50UHJv",
            "dG8SLgoMbG9jYWxBZGRyZXNzGAEgASgLMhgudGV4dHNlY3VyZS5BZGRyZXNz",
            "UHJvdG8SKwoIbWV0YWRhdGEYAiABKAsyGS50ZXh0c2VjdXJlLk1ldGFkYXRh",
            "UHJvdG8SNwoRbGVnYWN5RGF0YU1lc3NhZ2UYAyABKAsyGi5zaWduYWxzZXJ2",
            "aWNlLkRhdGFNZXNzYWdlSAASKQoHY29udGVudBgEIAEoCzIWLnNpZ25hbHNl",
            "cnZpY2UuQ29udGVudEgAQgYKBGRhdGEieQoNTWV0YWRhdGFQcm90bxIpCgdh",
            "ZGRyZXNzGAEgASgLMhgudGV4dHNlY3VyZS5BZGRyZXNzUHJvdG8SFAoMc2Vu",
            "ZGVyRGV2aWNlGAIgASgFEhEKCXRpbWVzdGFtcBgDIAEoAxIUCgxuZWVkc1Jl",
            "Y2VpcHQYBCABKAgiOQoMQWRkcmVzc1Byb3RvEgwKBHV1aWQYASABKAwSDAoE",
            "ZTE2NBgCIAEoCRINCgVyZWxheRgDIAEoCUJRCjpvcmcud2hpc3BlcnN5c3Rl",
            "bXMuc2lnbmFsc2VydmljZS5pbnRlcm5hbC5zZXJpYWxpemUucHJvdG9zUAGq",
            "AhBzZXJpYWxpemUucHJvdG9z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::libsignalservice.push.SignalServiceReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::serialize.protos.SignalServiceContentProto), global::serialize.protos.SignalServiceContentProto.Parser, new[]{ "LocalAddress", "Metadata", "LegacyDataMessage", "Content" }, new[]{ "Data" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::serialize.protos.MetadataProto), global::serialize.protos.MetadataProto.Parser, new[]{ "Address", "SenderDevice", "Timestamp", "NeedsReceipt" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::serialize.protos.AddressProto), global::serialize.protos.AddressProto.Parser, new[]{ "Uuid", "E164", "Relay" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class SignalServiceContentProto : pb::IMessage<SignalServiceContentProto> {
    private static readonly pb::MessageParser<SignalServiceContentProto> _parser = new pb::MessageParser<SignalServiceContentProto>(() => new SignalServiceContentProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SignalServiceContentProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::serialize.protos.InternalSerializationReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SignalServiceContentProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SignalServiceContentProto(SignalServiceContentProto other) : this() {
      localAddress_ = other.localAddress_ != null ? other.localAddress_.Clone() : null;
      metadata_ = other.metadata_ != null ? other.metadata_.Clone() : null;
      switch (other.DataCase) {
        case DataOneofCase.LegacyDataMessage:
          LegacyDataMessage = other.LegacyDataMessage.Clone();
          break;
        case DataOneofCase.Content:
          Content = other.Content.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SignalServiceContentProto Clone() {
      return new SignalServiceContentProto(this);
    }

    /// <summary>Field number for the "localAddress" field.</summary>
    public const int LocalAddressFieldNumber = 1;
    private global::serialize.protos.AddressProto localAddress_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::serialize.protos.AddressProto LocalAddress {
      get { return localAddress_; }
      set {
        localAddress_ = value;
      }
    }

    /// <summary>Field number for the "metadata" field.</summary>
    public const int MetadataFieldNumber = 2;
    private global::serialize.protos.MetadataProto metadata_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::serialize.protos.MetadataProto Metadata {
      get { return metadata_; }
      set {
        metadata_ = value;
      }
    }

    /// <summary>Field number for the "legacyDataMessage" field.</summary>
    public const int LegacyDataMessageFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::libsignalservice.push.DataMessage LegacyDataMessage {
      get { return dataCase_ == DataOneofCase.LegacyDataMessage ? (global::libsignalservice.push.DataMessage) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.LegacyDataMessage;
      }
    }

    /// <summary>Field number for the "content" field.</summary>
    public const int ContentFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::libsignalservice.push.Content Content {
      get { return dataCase_ == DataOneofCase.Content ? (global::libsignalservice.push.Content) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.Content;
      }
    }

    private object data_;
    /// <summary>Enum of possible cases for the "data" oneof.</summary>
    public enum DataOneofCase {
      None = 0,
      LegacyDataMessage = 3,
      Content = 4,
    }
    private DataOneofCase dataCase_ = DataOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DataOneofCase DataCase {
      get { return dataCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearData() {
      dataCase_ = DataOneofCase.None;
      data_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SignalServiceContentProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SignalServiceContentProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(LocalAddress, other.LocalAddress)) return false;
      if (!object.Equals(Metadata, other.Metadata)) return false;
      if (!object.Equals(LegacyDataMessage, other.LegacyDataMessage)) return false;
      if (!object.Equals(Content, other.Content)) return false;
      if (DataCase != other.DataCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (localAddress_ != null) hash ^= LocalAddress.GetHashCode();
      if (metadata_ != null) hash ^= Metadata.GetHashCode();
      if (dataCase_ == DataOneofCase.LegacyDataMessage) hash ^= LegacyDataMessage.GetHashCode();
      if (dataCase_ == DataOneofCase.Content) hash ^= Content.GetHashCode();
      hash ^= (int) dataCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (localAddress_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(LocalAddress);
      }
      if (metadata_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Metadata);
      }
      if (dataCase_ == DataOneofCase.LegacyDataMessage) {
        output.WriteRawTag(26);
        output.WriteMessage(LegacyDataMessage);
      }
      if (dataCase_ == DataOneofCase.Content) {
        output.WriteRawTag(34);
        output.WriteMessage(Content);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (localAddress_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LocalAddress);
      }
      if (metadata_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Metadata);
      }
      if (dataCase_ == DataOneofCase.LegacyDataMessage) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LegacyDataMessage);
      }
      if (dataCase_ == DataOneofCase.Content) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Content);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SignalServiceContentProto other) {
      if (other == null) {
        return;
      }
      if (other.localAddress_ != null) {
        if (localAddress_ == null) {
          LocalAddress = new global::serialize.protos.AddressProto();
        }
        LocalAddress.MergeFrom(other.LocalAddress);
      }
      if (other.metadata_ != null) {
        if (metadata_ == null) {
          Metadata = new global::serialize.protos.MetadataProto();
        }
        Metadata.MergeFrom(other.Metadata);
      }
      switch (other.DataCase) {
        case DataOneofCase.LegacyDataMessage:
          if (LegacyDataMessage == null) {
            LegacyDataMessage = new global::libsignalservice.push.DataMessage();
          }
          LegacyDataMessage.MergeFrom(other.LegacyDataMessage);
          break;
        case DataOneofCase.Content:
          if (Content == null) {
            Content = new global::libsignalservice.push.Content();
          }
          Content.MergeFrom(other.Content);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (localAddress_ == null) {
              LocalAddress = new global::serialize.protos.AddressProto();
            }
            input.ReadMessage(LocalAddress);
            break;
          }
          case 18: {
            if (metadata_ == null) {
              Metadata = new global::serialize.protos.MetadataProto();
            }
            input.ReadMessage(Metadata);
            break;
          }
          case 26: {
            global::libsignalservice.push.DataMessage subBuilder = new global::libsignalservice.push.DataMessage();
            if (dataCase_ == DataOneofCase.LegacyDataMessage) {
              subBuilder.MergeFrom(LegacyDataMessage);
            }
            input.ReadMessage(subBuilder);
            LegacyDataMessage = subBuilder;
            break;
          }
          case 34: {
            global::libsignalservice.push.Content subBuilder = new global::libsignalservice.push.Content();
            if (dataCase_ == DataOneofCase.Content) {
              subBuilder.MergeFrom(Content);
            }
            input.ReadMessage(subBuilder);
            Content = subBuilder;
            break;
          }
        }
      }
    }

  }

  public sealed partial class MetadataProto : pb::IMessage<MetadataProto> {
    private static readonly pb::MessageParser<MetadataProto> _parser = new pb::MessageParser<MetadataProto>(() => new MetadataProto());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MetadataProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::serialize.protos.InternalSerializationReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MetadataProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MetadataProto(MetadataProto other) : this() {
      _hasBits0 = other._hasBits0;
      address_ = other.address_ != null ? other.address_.Clone() : null;
      senderDevice_ = other.senderDevice_;
      timestamp_ = other.timestamp_;
      needsReceipt_ = other.needsReceipt_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MetadataProto Clone() {
      return new MetadataProto(this);
    }

    /// <summary>Field number for the "address" field.</summary>
    public const int AddressFieldNumber = 1;
    private global::serialize.protos.AddressProto address_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::serialize.protos.AddressProto Address {
      get { return address_; }
      set {
        address_ = value;
      }
    }

    /// <summary>Field number for the "senderDevice" field.</summary>
    public const int SenderDeviceFieldNumber = 2;
    private readonly static int SenderDeviceDefaultValue = 0;

    private int senderDevice_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int SenderDevice {
      get { if ((_hasBits0 & 1) != 0) { return senderDevice_; } else { return SenderDeviceDefaultValue; } }
      set {
        _hasBits0 |= 1;
        senderDevice_ = value;
      }
    }
    /// <summary>Gets whether the "senderDevice" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasSenderDevice {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "senderDevice" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearSenderDevice() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "timestamp" field.</summary>
    public const int TimestampFieldNumber = 3;
    private readonly static long TimestampDefaultValue = 0L;

    private long timestamp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Timestamp {
      get { if ((_hasBits0 & 2) != 0) { return timestamp_; } else { return TimestampDefaultValue; } }
      set {
        _hasBits0 |= 2;
        timestamp_ = value;
      }
    }
    /// <summary>Gets whether the "timestamp" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasTimestamp {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "timestamp" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearTimestamp() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "needsReceipt" field.</summary>
    public const int NeedsReceiptFieldNumber = 4;
    private readonly static bool NeedsReceiptDefaultValue = false;

    private bool needsReceipt_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool NeedsReceipt {
      get { if ((_hasBits0 & 4) != 0) { return needsReceipt_; } else { return NeedsReceiptDefaultValue; } }
      set {
        _hasBits0 |= 4;
        needsReceipt_ = value;
      }
    }
    /// <summary>Gets whether the "needsReceipt" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasNeedsReceipt {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "needsReceipt" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearNeedsReceipt() {
      _hasBits0 &= ~4;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MetadataProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MetadataProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Address, other.Address)) return false;
      if (SenderDevice != other.SenderDevice) return false;
      if (Timestamp != other.Timestamp) return false;
      if (NeedsReceipt != other.NeedsReceipt) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (address_ != null) hash ^= Address.GetHashCode();
      if (HasSenderDevice) hash ^= SenderDevice.GetHashCode();
      if (HasTimestamp) hash ^= Timestamp.GetHashCode();
      if (HasNeedsReceipt) hash ^= NeedsReceipt.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (address_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Address);
      }
      if (HasSenderDevice) {
        output.WriteRawTag(16);
        output.WriteInt32(SenderDevice);
      }
      if (HasTimestamp) {
        output.WriteRawTag(24);
        output.WriteInt64(Timestamp);
      }
      if (HasNeedsReceipt) {
        output.WriteRawTag(32);
        output.WriteBool(NeedsReceipt);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (address_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Address);
      }
      if (HasSenderDevice) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SenderDevice);
      }
      if (HasTimestamp) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Timestamp);
      }
      if (HasNeedsReceipt) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MetadataProto other) {
      if (other == null) {
        return;
      }
      if (other.address_ != null) {
        if (address_ == null) {
          Address = new global::serialize.protos.AddressProto();
        }
        Address.MergeFrom(other.Address);
      }
      if (other.HasSenderDevice) {
        SenderDevice = other.SenderDevice;
      }
      if (other.HasTimestamp) {
        Timestamp = other.Timestamp;
      }
      if (other.HasNeedsReceipt) {
        NeedsReceipt = other.NeedsReceipt;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (address_ == null) {
              Address = new global::serialize.protos.AddressProto();
            }
            input.ReadMessage(Address);
            break;
          }
          case 16: {
            SenderDevice = input.ReadInt32();
            break;
          }
          case 24: {
            Timestamp = input.ReadInt64();
            break;
          }
          case 32: {
            NeedsReceipt = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  public sealed partial class AddressProto : pb::IMessage<AddressProto> {
    private static readonly pb::MessageParser<AddressProto> _parser = new pb::MessageParser<AddressProto>(() => new AddressProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AddressProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::serialize.protos.InternalSerializationReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AddressProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AddressProto(AddressProto other) : this() {
      uuid_ = other.uuid_;
      e164_ = other.e164_;
      relay_ = other.relay_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AddressProto Clone() {
      return new AddressProto(this);
    }

    /// <summary>Field number for the "uuid" field.</summary>
    public const int UuidFieldNumber = 1;
    private readonly static pb::ByteString UuidDefaultValue = pb::ByteString.Empty;

    private pb::ByteString uuid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Uuid {
      get { return uuid_ ?? UuidDefaultValue; }
      set {
        uuid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "uuid" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasUuid {
      get { return uuid_ != null; }
    }
    /// <summary>Clears the value of the "uuid" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearUuid() {
      uuid_ = null;
    }

    /// <summary>Field number for the "e164" field.</summary>
    public const int E164FieldNumber = 2;
    private readonly static string E164DefaultValue = "";

    private string e164_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string E164 {
      get { return e164_ ?? E164DefaultValue; }
      set {
        e164_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "e164" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasE164 {
      get { return e164_ != null; }
    }
    /// <summary>Clears the value of the "e164" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearE164() {
      e164_ = null;
    }

    /// <summary>Field number for the "relay" field.</summary>
    public const int RelayFieldNumber = 3;
    private readonly static string RelayDefaultValue = "";

    private string relay_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Relay {
      get { return relay_ ?? RelayDefaultValue; }
      set {
        relay_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "relay" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasRelay {
      get { return relay_ != null; }
    }
    /// <summary>Clears the value of the "relay" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearRelay() {
      relay_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AddressProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AddressProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Uuid != other.Uuid) return false;
      if (E164 != other.E164) return false;
      if (Relay != other.Relay) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (HasUuid) hash ^= Uuid.GetHashCode();
      if (HasE164) hash ^= E164.GetHashCode();
      if (HasRelay) hash ^= Relay.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (HasUuid) {
        output.WriteRawTag(10);
        output.WriteBytes(Uuid);
      }
      if (HasE164) {
        output.WriteRawTag(18);
        output.WriteString(E164);
      }
      if (HasRelay) {
        output.WriteRawTag(26);
        output.WriteString(Relay);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (HasUuid) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Uuid);
      }
      if (HasE164) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(E164);
      }
      if (HasRelay) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Relay);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AddressProto other) {
      if (other == null) {
        return;
      }
      if (other.HasUuid) {
        Uuid = other.Uuid;
      }
      if (other.HasE164) {
        E164 = other.E164;
      }
      if (other.HasRelay) {
        Relay = other.Relay;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Uuid = input.ReadBytes();
            break;
          }
          case 18: {
            E164 = input.ReadString();
            break;
          }
          case 26: {
            Relay = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
